name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.4.app
    - name: Run CI script
      run: ./scripts/run_ci.sh
